Image cropping
Space-Runners/ablo-demo-fe pull request #133
Opened 2023-11-08 19:18 UTC by airmiha

### Description (what's changed?)

Ability to crop image for image to image by pan and zoom.

2023-11-08 19:18 UTC, kvarela commented
Task linked: [CU-86aykjmze Implement image cropping tool for image to image](https://app.clickup.com/t/86aykjmze)

2023-11-08 19:18 UTC, kvarela commented
Task linked: [CU-86aykjmze Implement image cropping tool for image to image](https://app.clickup.com/t/86aykjmze)

2023-11-08 22:40 UTC, kvarela requested changes

2023-11-08 22:40 UTC, kvarela commented on src/lib/editor/toolbar/image-to-image/cropImage.ts
> +    image.setAttribute('crossOrigin', 'anonymous'); // needed to avoid cross-origin issues on CodeSandbox
Is this still necessary?

2023-11-08 22:40 UTC, kvarela commented on src/lib/editor/toolbar/image-to-image/index.tsx
> +      console.error(e);
Should probably show an error toast or something if this doesn't work

2023-11-09 13:58 UTC, btosic approved these changes

2023-11-09 14:58 UTC, kvarela approved these changes

2023-11-09 14:58 UTC, merged